version: '3'
services:
  mongo:
    container_name: mongo
    image: olejekglejek/eng84_node_app
    build: ./db
    ports:
      - '27017:27017'
  app:
    container_name: app
    image: olejekglejek/eng84_mongodb

    build: ./app
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./app:/test
