apiVersion: v1
kind: Namespace
metadata:
  name: flask
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: flask-app
        image: eng84/flask:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: flask
spec:
  # type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol:
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: flask
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: flask-svc
          servicePort: 80
